### ISSUE TITLE
Does not build on Debian Stretch (libboost 1.62)

### ISSUE THREAD

**Issue by Senso** [MultiChain/multichain#24]
Getting a lot of errors similar to this:

chainparams/chainparams.cpp:177:51: error: ambiguous overload for ‘operator=’ (operand types are ‘std::vector<unsigned char>’ and ‘boost::assign_detail::generic_list<int>’)
         base58Prefixes[SCRIPT_ADDRESS] = list_of(5);
                                                   ^
In file included from /usr/include/c++/6/vector:69:0,
                 from ./chainparams/chainparamsbase.h:10,
                 from ./chainparams/chainparams.h:10,
                 from chainparams/chainparams.cpp:7:
/usr/include/c++/6/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~
